### ISSUE TITLE
Feature Request: Define a list width

### ISSUE THREAD

**Issue by IvoPereira** [TerryZ/v-selectpage#1]
Hello,

I would like to suggest the ability to add a fixed width to the list. Otherwise, when you go through different pages, the container will always keep changing the width and that does not provide a good user experience.

Thanks

**Comment by TerryZ** [comment]
You must be talking about table view mode of list?

**Comment by IvoPereira** [comment]
Exactly @TerryZ.

**Comment by TerryZ** [comment]
added `width` option in last release

**Comment by Anima-No** [comment]
@TerryZ  对表格某个列进行排序，这个表格应用的比较多，可以配置在tb-columns
