### ISSUE TITLE
Feature Request: AppendTo property

### ISSUE THREAD

**Issue by enghelewa** [TerryZ/v-selectpage#12]
I am working on a website with RTL interface. And Unfortunately this beautiful component plugin doesn't support RTL languages.

So I thought providing a feature like `appendTo` which enables me to append the list to the current parent will help me to override some css properties to make it possible to show the list in a proper way inside an RTL interface.

**Comment by TerryZ** [comment]
If only RTL for result list, you can set a css style content to override in your page/component:

```css
.sp-result-area .sp-reaults li {
    direction: rtl;
}
```

**Comment by enghelewa** [comment]
@TerryZ  I found that we could get benefit of `position` property of `Dropdown` component you used within `SelectPage` so I'v created a PR #13 also I'v added Arabic translation here #11.

I think that will be enough to make it work in RTL interfaces. It may require adding css style to the component to indicate RTL and everything will work fine :)

**Comment by TerryZ** [comment]
Ok, will add `rtl` option to set result list text direction and make it can config in plugin install for global setting in next release, stay tuned.

```js
Vue.use(SelectPage, { rtl: true });
```

**Comment by TerryZ** [comment]
add `rtl` option in last release(`2.0.2`)
