### ISSUE TITLE
Selectpage's v-model overrides the default value continued...

### ISSUE THREAD

**Issue by SanjayBanjade** [TerryZ/v-selectpage#15]
Thank you very much for the fix #8 . I think it has helped.

I do experience the same behavior time to time though. I had to apply a temporary fix to make the component work in my application.

    watch: {
        'models'() {
            if(Object.keys(this.models).length > 0) {
                setTimeout(() => {
                    this.input.model_id = this.settings.properties.model_id
                }, 0)
            }
        }
    }
So, when the data arrives, I simply assign the selected model id to input.model_id because at first this component tries to overrides input.model_id to an empty string. This way with setTimeout(fn, 0), I applied a temporary fix!

Can you tell me if I'm doing something wrong or not using your component properly?

**Comment by SanjayBanjade** [comment]
Hi @TerryZ ! Sorry for the super-late reply. I created the sandbox for this issue. Here's the link: https://codesandbox.io/s/q70yv7lvyq?fontsize=14

So, there's a modal and inside modal there are two tabs: `Tab1` and `Tab 2`. Now if you click on `Tab 2`, there's `v-selectpage` component. At first you can see the value is selected with no problem. However, if you click on `Tab1` and go back to `Tab 2`, there's no any value selected. It's just empty.

Click back and forth and you can see the issue.

**Comment by SanjayBanjade** [comment]
@TerryZ Has this test sample been useful or do I need to create another sample to showcase the problem? 

What do you think?

**Comment by TerryZ** [comment]
@SanjayBanjade upgrade v-selectpage to `2.1.0` and try again, may solved your problem.

**Comment by TerryZ** [comment]
> Hi @TerryZ ! Sorry for the super-late reply. I created the sandbox for this issue. Here's the link: https://codesandbox.io/s/q70yv7lvyq?fontsize=14
> 
> So, there's a modal and inside modal there are two tabs: `Tab1` and `Tab 2`. Now if you click on `Tab 2`, there's `v-selectpage` component. At first you can see the value is selected with no problem. However, if you click on `Tab1` and go back to `Tab 2`, there's no any value selected. It's just empty.
> 
> Click back and forth and you can see the issue.

Try this:

1. change `v-if` to `v-show`

```vue
<div class="tab-content" style="margin-top: 3rem">
  <Tab1 v-show="activeTab === 1"/>
  <Tab2 v-show="activeTab === 2" :todos="todos" :todoId="todo.id"/>
</div>
```

2. Reset todo id

```js
  watch: {
    activeTab() {
      if (this.activeTab === 2) {
        this.todo.id = "";//reset id
        this.fetchTodo();
      }
    }
  }
```

**Comment by vowave** [comment]
This issue still remains and the v-show method makes the page really heavy when you load a few tabs together.
