### ISSUE TITLE
表格显示模式下，服务端获取数据，选择数据后，组件value值不对

### ISSUE THREAD

**Issue by gagaboy** [TerryZ/v-selectpage#2]
表格显示模式下，服务端获取数据，选择数据后，组件value值不对
组件的value值非当前选中的那条记录，而是当前页的记录主键的逗号隔开的字符串

**Comment by TerryZ** [comment]
注意指定结果集中的 `key-field` 和 `show-field`

**Comment by gagaboy** [comment]
不好意思  没太明白你说的结果集中的key-field 和 show-field，我在组件中不是已经指定过了么  能够给我一个请求的数据格式 标准的
或者v-selectpage能否加些demo的代码参考下

> 在 2018年7月29日，下午2:47，Terry Zeng <notifications@github.com> 写道：
> 
> 注意指定结果集中的 key-field 和 show-field

**Comment by TerryZ** [comment]
官网的DEMO不论是具体使用方式，还是服务端应返回的格式，还是针对返回数据的格式化，都作了说明
