### ISSUE TITLE
V-model and async messed up selected value

### ISSUE THREAD

**Issue by tanyudii** [TerryZ/v-selectpage#24]
Hi, sorry if this topic already discussed but as I see most of them are in Chinese which I don't understand. I have difficulties in selecting the value when I use v-model and aysnc request to server for the data. The values selected are all replaced by the values from the server. If I see the log, everytime I select an option, it requests to server again. Thanks

```vue
<no-ssr placeholder="Loading...">
	<v-selectpage :data="MY_SERVER_ENDPOINT"
				  name="currency"
				  show-field="name"
				  title="Select Currency"
				  v-model="asd"
				  search-field="keyword"
				  @values="changeData"
				  :result-format="resultFormat">
	</v-selectpage>
</no-ssr>
```

**Comment by TerryZ** [comment]
What version of `v-selectpage` are you using now?

**Comment by tanyudii** [comment]
I'm using `"v-selectpage": "^2.0.2"`

**Comment by tanyudii** [comment]
> What version of `v-selectpage` are you using now?

I'm using `v-selectpage v2.0.2`,

this is my example in sandbox
[https://codesandbox.io/s/2jxx9o1yjn](url)

**Comment by shiayoung** [comment]
+1

**Comment by andrewjackroyd** [comment]
Hi, will this be resolved?

**Comment by tanyudii** [comment]
> Hi, will this be resolved?

i'don't know, me to waiting for update

**Comment by TerryZ** [comment]
I was been busy these days, really sorry.

**Comment by NeilMaude** [comment]
Hi, do you have an estimate when this might be resolved?

**Comment by TerryZ** [comment]
@tanyudii @andrewjackroyd @NeilMaude @shiayoung 

Please upgrade v-selectpage to `2.1.0` to solved this problem.
