### ISSUE TITLE
selectPage 分页单选模式选中其中一条数据，会默认当前页全部被选中

### ISSUE THREAD

**Issue by weianke** [TerryZ/v-selectpage#28]
v-model 不能正确显示选中的值，选中后会把当前页的10条数据全部选中，
使用@values 可以新增
但是如果回显，默认选择就没有办法可以选中，严重BUG
![1](https://user-images.githubusercontent.com/15901398/57215978-15979c80-7021-11e9-9a5c-a0e3e6ff59f6.png)

**Comment by zaofanjun** [comment]
这个bug我在半年前发有限给作者，他也回复说能修复，结果半年以后我又要来用了，结果发现还是老样子，选择就是全选了，无敌bug

**Comment by TerryZ** [comment]
@zaofanjun 这位同学，我真是很不愿意去怼你，但你的口气还是让人很恼火！

在很多其他 issue 和 pull request 里有提到，我现在的工作也很忙，你有你的工作，我也有我的工作，工作优先应该没人有意见吧？

你的语气，居高临下的感觉，看完我马上就开始回忆是不是收了你钱了，还是欠了你钱了，没有任何一个开源作者会喜欢你这样的话语。

如果你有能力，你完全可以 fork 代码，解决问题，再 pull request，这是很多国外开发者在我的项目里的参与方式，提高国人程序员的能力和素质要从你我做起！一激动就说多了。

我的回复依然是：一定会解决问题，但时间上不好说

**Comment by TerryZ** [comment]
@weianke 服务端数据模式下，若已设置初始化值（v-model/value 指定了相应的值），那么插件需要根据这些指定的值，获得相应的详细信息，因为这些内容很有可能不在当前页，所以此时会发起两次请求

1. 请求参数中增加 `searchKey` 与 `searchValue` 两个项目，前者传递了 `keyField` 指定的字段名，后者传递后了当前 `v-model/value` 的值，所以要求服务端要获取这两个参数，并将相应的数据返回给插件，插件会将这些数据作为选中项目，设置在选中内容区域中（select/tags）
2. 常规列表数据请求

你的截图里，全部项目都变成了灰色，显然是你的服务端没有处理选择项目的内容匹配
