### ISSUE TITLE
How to change language to English

### ISSUE THREAD

**Issue by nobleson** [TerryZ/v-selectpage#35]
I have issue configuring the language option to English.
`   import vSelectPage from 'v-selectpage';
    Vue.use(vSelectPage, {lang:'en'})
;`
It is display the default Chinese

**Comment by TerryZ** [comment]
Try below:

```js
import Vue from 'vue';
import selectpage from 'v-selectpage';

Vue.use(selectpage, {
    language:'en'
});
```

**Comment by nobleson** [comment]
Than you @TerryZ .
Every thing is okay.
But how can i show table view, hence the desc?
Thanks

**Comment by nobleson** [comment]
Than you @TerryZ .
Every thing is okay.
But how can i show table view, hence the desc?
Thanks

**Comment by TerryZ** [comment]
The `v-selectpage` display by table view demo:

```vue
<template>
    <v-selectpage :data="sample1" :tb-columns="columns">
    </v-selectpage>
</template>
 
<script>
export default {
    data(){
        return {
            sample1: [
                {id:1 ,name:'The People\'s Republic of China',desc:'中华人民共和国'},
                {id:2 ,name:'United States of America',desc:'美利坚合众国'},
                {...}
            ],
            columns:[
                {title: 'id',data: 'id'},
                {title: 'name',data: 'name'},
                {title: 'desc',data: 'desc'},
            ]
        }
    }
};
</script>
```

More detail please visit: [selectpage-demo](https://terryz.github.io/vue/#/selectpage/demo)

**Comment by nobleson** [comment]
Thank you alot.
