### ISSUE TITLE
Server-side rendering of items overrides the default value

### ISSUE THREAD

**Issue by SanjayBanjade** [TerryZ/v-selectpage#36]
When I use server-side rendering in selectpage, it overrides the default value to the all the items in the first page.

I created a sandbox for this:
https://codesandbox.io/embed/vue-template-43660

Is this a bug or am I doing something wrong?

**Comment by SanjayBanjade** [comment]
I think it refers to #24. Sorry I didn't see that ticket and created a new one.

**Comment by TerryZ** [comment]
There are two things need to do in server-side

1. load selected items raw data
2. load current page data

Have some code for example(`Java`):

```java
public void loadUsers(){
    StringBuilder sb = new StringBuilder();
    List<Object> params = new ArrayList<Object>();
    //for query selected items
    //searchKey = search-field
    //searchValue = what you entered text
    if(StringUtils.isNotEmpty(getPara("searchKey")) && StringUtils.isNotEmpty(getPara("searchValue"))){
        String value = getPara("searchValue");
        String[] valuearr = value.split(",");
        String searchStr = "";
        for(String val : valuearr){
            if(searchStr.length() != 0) searchStr += ",";
            searchStr += "?";
            params.add(val);
        }
        sb.append(" and " + getPara("searchKey") + " in (" + searchStr + ")" );
    }
    this.getPageInfo();
    Page<Record> plist = Db.paginate(this.getPage(),
                                     this.getPageSize(),
                                     "select *","from user where 1=1 " + sb.toString(),
                                     params.toArray());
 
    renderJson(plist);
}
```
When selected some items, save data form, refresh page, you can observe the http request record in the `Network` panel of Chrome developor tools, It will have 2 http request record.

**Comment by SanjayBanjade** [comment]
Yup, there's 2 request done. Just verified.

**Comment by TerryZ** [comment]
So you need to same thing in your server-side.

**Comment by SanjayBanjade** [comment]
I am loading the list data and the selected data from the server. But why is it executing 2 requests to the same API? I didn't get that.

**Comment by TerryZ** [comment]
You must have chosen some items, one of request is going to load selected items raw data. Because your chosen items not necessarily in current page.

**Comment by SanjayBanjade** [comment]
Okay if so, then it shouldn't select anything itself right? Because currently it selects all the items of the first page. And the list items becomes disabled as well.

**Comment by TerryZ** [comment]
Just like last time, upload your code to sandbox and i can see what happened.

**Comment by FeSongSong** [comment]
![image](https://user-images.githubusercontent.com/19163781/97947269-b5c1b380-1dc7-11eb-90c3-8cde7ab50ecf.png)
