### ISSUE TITLE
进入页面赋初始化值有问题

### ISSUE THREAD

**Issue by Anima-No** [TerryZ/v-selectpage#45]
代码如附件，我进入页面给realmId 赋值为1192013224205352962
但是我上面的/live_code/codeliverealm/list 返回的数值是
0.
{realmId: "1192011114952785921"
realmUrl: (...)
}
1:
{realmId: "1192013224205352962"
realmUrl: (...)
}
假设这里有两笔数据
此时我们看realmId的值他就发生了变化，成了realmId:"1192011114952785921,1192013224205352962"

变成了两个ID了？？？？？这要重新选择下拉框。realmId的值才能变成变成单个，而不是现在有两个。不知道为什么这里会这样？有没有人遇到过这样的问题，如果你进页面不赋值的话，就没问题，

[demo.txt](https://github.com/TerryZ/v-selectpage/files/3817754/demo.txt)

**Comment by TerryZ** [comment]
#36

**Comment by Anima-No** [comment]
> 参考前面的问题：
> [＃36（评论）](https://github.com/TerryZ/v-selectpage/issues/36#issuecomment-514562603)
> 
> 服务端除了提供正常的列表数据外，也需要处理预定的`searchKey`和`searchValue`，它们指定了具体的查询细分和查询值，在服务里，应该被处理为以下的SQL内容
> 
> ```
> select xxx from xxx where the_search_key=the_search_value
> ```
> 
> 这些内容只需要在原来查询列表的服务端处理逻辑中增加该两个细分的捕获并处理即可
> 
> 作用当然是用来重新获取已替代项目的清单的，因为列表只会显示一页的数据，而您选择的数据，并不一定在当前页

Thank you, it has been solved, it is the server did not capture the field, thank you again!

**Comment by Anima-No** [comment]
> > 参考前面的问题：
> > [＃36（评论）](https://github.com/TerryZ/v-selectpage/issues/36#issuecomment-514562603)
> > 服务端除了提供正常的列表数据外，也需要处理预定的`searchKey`和`searchValue`，它们指定了具体的查询分段和查询值，在服务里，应该被处理为以下的SQL内容
> > ```
> > select xxx from xxx where the_search_key=the_search_value
> > ```
> > 
> > 
> > 这些内容只需要在原来查询列表的服务端处理逻辑中增加该两个细分的捕获并处理即可
> > 作用当然是重新重新获取已替代项目的清单的，因为列表只会显示一页的数据，而您选择的数据，且不一定在当前页
> 
> 谢谢，已经解决了，是服务器没有捕获到该字段，再次谢谢！

你好，我不想用searchKey, searchValue这两个值，我想用 search-field="realmUrl"  realmUrl这个作为searchKey，可以吗

**Comment by TerryZ** [comment]
`searchKey` 这个参数，默认使用了 `key-field` 指定的字段，但如果设置了 `search-field` 字段，会优先使用后者指定的字段

**Comment by FeSongSong** [comment]
> `searchKey` 这个参数，默认使用了 `key-field` 指定的字段，但如果设置了 `search-field` 字段，会优先使用后者指定的字段

大佬 我设置了search-field 还是用的key-field 这个是什么问题
