### ISSUE TITLE
v-selectpage 打包后的问题 

### ISSUE THREAD

**Issue by jasonlan-design** [TerryZ/v-selectpage#56]
我的项目是vue+element-ui的项目，我想问下是否依赖element-ui,为了优化性能   #我把element-ui改成cdn链接，并且把main.js里面引入element-ui给注释，在webpack配置里用了externals,但是打包后此组件的input框没有出来，找了好久没有找到原因，请教一下原因。
![Uploading 02eb38f0505
![0e1c0cc0116b49fe91de1583f21e3e5](https://user-images.githubusercontent.com/65838890/97651151-429e0180-1a96-11eb-88a6-9e5e35b420fe.png)
![4589fc616340d86cbaa25563b833fb7](https://user-images.githubusercontent.com/65838890/97651154-45005b80-1a96-11eb-9e45-4738c4586410.png)

3f6c3d55de4c966b7e18.png…]()

**Comment by TerryZ** [comment]
`v-selectpage` 是通用组件，没有依赖任何 UI 框架

**Comment by jasonlan-design** [comment]
有个好奇怪的问题  我这样子的形式打包后。就变成了这样子了 
![Uploading 微信图片_202010300954373.png…]()

**Comment by jasonlan-design** [comment]
![d582b6dee22442ea4c9fa263fd00485](https://user-images.githubusercontent.com/65838890/97652474-69116c00-1a99-11eb-9672-f6223057aaa3.png)
就是箭头所指这个  我按照我如上那种打包方式 就出不来

**Comment by jasonlan-design** [comment]
下面那块搜索框加载数据都没有问题  而且数据绑定也没有问题  就是这个展示有问题

**Comment by TerryZ** [comment]
插件的样式被你项目中的全局环境给污染（覆盖），用浏览器的元素选择器查看下就知道了
