### ISSUE TITLE
怎么设置成行内元素？

### ISSUE THREAD

**Issue by mrtr9** [TerryZ/v-selectpage#58]
display:inline;没有任何效果

**Comment by TerryZ** [comment]
没头没尾来这么一句，简直莫明其妙！沟通问题至少要描述清楚场景，需求，问题，再配合截图才可以快速把你想表达的东西描述清楚

**Comment by mrtr9** [comment]
我希望把v-selectpage 设置成行内元素，可以让span标签跟v-selectpage在同一行显示
