### ISSUE TITLE
dataload and v-model 有bug

### ISSUE THREAD

**Issue by xxShawn** [TerryZ/v-selectpage#6]
remote 方法的 最后一行代码 
`that.picked = tmpObj.list`， 页面全选中了，没有看明白这里要干啥

我使用 v-model 远程加载， dataload是一个url，

选中一项之后， 会触发 watch->picked 方法
    picked(val) {
      if (this.message && this.maxSelectLimit && val.length < this.maxSelectLimit) this.message = ''
      let that = this
      this.$emit('input', val.map((value) => value[that.keyField]).join(','))
      this.$emit('values', this.picked.concat())
    },

通过v-modal ，该组件接受的value改变，触发
watch->value ->this.initSelection 然后走到remote的最后一行， 导致页面全选了

**Comment by xxShawn** [comment]
initselection 方法 存在多次执行remote方法的 情况。
initselection->remote
initseelction->populate->remote

**Comment by xxShawn** [comment]
想了一下， 应该存在这一样一个问题

选中项值使用的 picked，
v-model 绑定的是value，
当选中一项，picked改变时，触发input，父组件的v-model变化，传给该组件一个新的value，导致触发watch->value

选中项 value和picked 统一起来应该好一点吧

**Comment by TerryZ** [comment]
找时间验证一下

**Comment by rlightner** [comment]
This is occuring for me as well.

**Comment by TerryZ** [comment]
fixed in last release
