### ISSUE TITLE
Selectpage's v-model overrides the default value

### ISSUE THREAD

**Issue by SanjayBanjade** [TerryZ/v-selectpage#8]
I load data from the server and only after the data arrives, I render the `v-selectpage` component using `v-if`. The `v-model` of the component is bind to `selected_model`. At first, the `selected_model` is `24`. However, the component overrides the `selected_model` to empty string. 

Is this the intended behavior?

**Comment by vstath** [comment]
I experience the same issue. @TerryZ where should I look in the code to fix the bug? Any pointers? Thanks

**Comment by TerryZ** [comment]
This issues will be fixed in next release, please wait patiently, Thanks.

**Comment by TerryZ** [comment]
fixed in last release
